name: booking_api
description: Booking API REST server with SQLite
version: 1.0.0

environment:
  sdk: ^3.0.0

dependencies:
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  sqlite3: ^2.4.6
  dart_jsonwebtoken: ^2.14.1
  crypto: ^3.0.5
